install: composer install --prefer-source --dev

services:
  - memcache

env: PHPAR_MYSQL=mysql://root@127.0.0.1/phpar_test PHPAR_PGSQL=pgsql://postgres@127.0.0.1/phpar_test

language: php
php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  include:
    - php: 7.0
      env: PHPAR_MYSQL=mysql://root@127.0.0.1/phpar_test PHPAR_PGSQL=pgsql://postgres@127.0.0.1/phpar_test EXTENSION=memcached
    - php: 7.1
      env: PHPAR_MYSQL=mysql://root@127.0.0.1/phpar_test PHPAR_PGSQL=pgsql://postgres@127.0.0.1/phpar_test EXTENSION=memcached
    - php: nightly
      env: PHPAR_MYSQL=mysql://root@127.0.0.1/phpar_test PHPAR_PGSQL=pgsql://postgres@127.0.0.1/phpar_test EXTENSION=memcached
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo 'extension = "${EXTENSION:-memcache}.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - mysql -e 'CREATE DATABASE phpar_test;'
  - psql -c 'CREATE DATABASE phpar_test;' -U postgres

script: ./vendor/bin/phpunit
